sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build -v
  - git config user.name "Travis" && git config user.email "lucio.franco@du.edu" 
  - cd tests && ./test.sh