sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - if [[ "$(rustc --version)" =~ -(dev|nightly) ]]; then cargo build -v --features clippy; else cargo build -v; fi && cd tests && ./test.sh