[package]
name = "ghp"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Lucio Franco <lucio.franco@du.edu>"]

[dependencies]
getopts = "0.2"
walkdir = "0.1.5"
clippy = {version="*", optional=true}